### ISSUE TITLE
Something wrong with this dataset compared to what paper written

### ISSUE THREAD

**Issue by thaodod** [nikitalpopov/vedai#3]
1/ Only 9 classes in original paper: Boat, Camping Car, Car, Pickup, Plane, Tractor, Truck, Vans, Others. (There's no BUS!) while this repo has 3 images contain Bus!
2/ Small & Large Land Vehicle is just another way of categorization. BUT, in this repo, they're categorized into the 2 last classes and there's no extra specific classified for them.
I checked with original annotations from their official website and the problem is original author.
So keep this issue in mind when consider using this dataset. (this way of categorization is confusing)

**Comment by nikitalpopov** [comment]
Hi @doduythao 
Could you, please, mark at any specific images I should check?
When I was creating this repo there were following classes listed (I can't recall source atm):

- 1: car,
- 2: trucks,
- 4: tractors,
- 5: camping cars,
- 7: motorcycles,
- 8: buses,
- 9: vans,
- 10: others,
- 11: pickup,
- 23: boats,
- 201: Small Land Vehicles,
- 31: Large land Vehicles

Since attention to this repo is increasing, I will try to correct data

**Comment by thaodod** [comment]
I checked and the problem is the inconsistency between their paper and their dataset. Not your fault but you should also remove Bus class since it's very small 3 image contain it. So anyone use this dataset should just remove all image containing SLV and LLV since this gonna confuse the model (doesn't make any sense to classify one superclass and subclasses, even hurt the model)

**Comment by mowushuang** [comment]
ok ,i will remove other class. thanks!
